# Generated by Django 4.0.2 on 2022-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_representer',
        ),
        migrations.AddField(
            model_name='course',
            name='class_representer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='class_representer_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
