# Generated by Django 4.0.2 on 2022-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0002_remove_course_class_representer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
