# Generated by Django 4.0.2 on 2022-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0003_alter_course_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
