# Generated by Django 4.0.2 on 2022-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0004_chapter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
