# Generated by Django 4.0.2 on 2022-05-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0006_chapter_created_at_classwork_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulecrud.course_status'),
        ),
    ]
