# Generated by Django 4.0.2 on 2022-07-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulecrud', '0009_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulecrud.semester'),
        ),
    ]
